### ISSUE TITLE
Improving lowercase Cyrillic glyps localized for Macedonian and Serbian

### ISSUE THREAD

**Issue by dimztimz** [liberationfonts/liberation-fonts#10]
These glyph are used with the OpenType feature known as "locl substitutions". The chars in question are: б, г, д, ѓ, п, т, ш.

Macedonian and Serbian language allows them to be different in serif italic (cursive) than the Russian cursive, but does not mandate. A detailed discussion for that is present in the Serbian orthography book from 1994. The most complete reference can be found in this image:

![alternative localized italic Cyrillic glyphs for Macedonian and Serbian](https://upload.wikimedia.org/wikipedia/commons/7/71/Cyrillic_cursive.svg)

As one can see BE (б) has two options. The conservative and the vastly widespread option is to use BE that looks like six. Since Liberation fonts are conservative fonts, we will use the six look.

So fast Liberation already has some of these right, but some of them are wrong. I already fixed the BE for regular. Thanks for accepting that patch 83e68a41f963e0554b90c6815619b6551117574a. In the future I will try to fix the others.

Here is a list of bugs that need fixing:

- [x] BE (б) in any regular does not need localization
- [x] BE (б) in any italic does not need localization (I already made a pull request for this)
- [x] Mono italic does not need any localized shapes whatsoever. (same pull request as above)
- [x] GE (г) in Sans Italic does not need any localization. i with a macron is just wrong. (same pull request as above)
- [ ] GE (г) in Serif Italic needs improvements.
- [ ] GJE (ѓ) in Serif italic needs to be harmonized with GE.

Cyrillic DE, PE, TE, SHA (д, п, т, ш) are mostly OK, may need some fixing but are less critical.

**Comment by vishalvvr** [comment]
Thank you for the PR, bug fixed in 2.00.5 release.
