### ISSUE TITLE
COMBINING LONG SOLIDUS OVERLAY (U+0338) not centred on base character

### ISSUE THREAD

**Issue by jayfoad** [liberationfonts/liberation-fonts#13]
NOT IDENTICAL TO (U+2262) has the decomposition IDENTICAL TO (U+2261), COMBINING LONG SOLIDUS OVERLAY (U+0338). And the Unicode code charts clearly show that the combining long solidus should be centred on the base character. But when I try displaying the sequence U+2261, U+0338 with Liberation Sans, the solidus appears to the right of the base character, like this:
![screenshot from 2019-02-06 15-23-39](https://user-images.githubusercontent.com/108316/52351715-36048a80-2a23-11e9-81c6-6cb6a705e0e5.png)
I've tried rendering it with Chrome and with https://fontdrop.info/.

This was with version 2.00.1-7 of Ubuntu 18.10's fonts-liberation2 package, but the LiberationSans-Regular.ttf therein seems to self-identify as version 2.00.2.

**Comment by jayfoad** [comment]
See also https://bugzilla.redhat.com/show_bug.cgi?id=1072095. The comparison.png attached there shows the letter g combining badly with various combining characters including U+0338.

**Comment by vishalvijayraghavan** [comment]
Hi Jayfoad,
Thanks for reporting this bug, actually this glyph(U+2262) was missing in liberation-fonts and applying normalization technique font used to render U+2261 + U+0338.
I have added a new glyph(U+2262) now you may test it :)

**Comment by jayfoad** [comment]
Thanks, I know that U+2262 was missing. But why doesn't U+2261 + U+0338 render correctly?

**Comment by vishalvijayraghavan** [comment]
This two glyphs U+2261 & U+0338 are independent glyphs so they would render one after the other in sequence, but if you want to render it by overlapping two glyphs then that can be achieved by writing rule(by adding anchor) or create new glyph :)

**Comment by vishalvijayraghavan** [comment]
Fixed in liberation-fonts 2.00.5 version
