### ISSUE TITLE
liberation mono fonts are not recognized as monospace by fontconfig and cairo

### ISSUE THREAD

**Issue by rschupp** [liberationfonts/liberation-fonts#14]
When configuring gnome-terminal I noticed that the Gtk font chooser wouldn't show
the liberation mono fonts (though they were installed). The chooser filters for
monospaced fonts and doesn't recognize liberation mono fonts as such.
It's using pango_font_family_is_monospace() from Pango which in turn
uses fontconfig to check for spacing == FC_MONO, basically meaning all glyphs have the same width.

The fonts fail the latter because they contain
exactly one glyph that has a width different from all others: glyph ID 2394 "uni20BF"  (Bitcoin Sign).

**Comment by georgeabr** [comment]
Any progress on this?

**Comment by vishalvvr** [comment]
fix available in 2.1.2 release.
Thank you for reporting.
