### ISSUE TITLE
Incorrect glyph name mapped to unicode

### ISSUE THREAD

**Issue by vishalvvr** [liberationfonts/liberation-fonts#19]
When opening font file with fontforge(any weight) gives following warning:
  
The glyph named macron is mapped to U+02C9.
But its name indicates it should be mapped to U+00AF.
The glyph named Delta is mapped to U+0394.
But its name indicates it should be mapped to U+2206.
The glyph named Omega is mapped to U+03A9.
But its name indicates it should be mapped to U+2126.
The glyph named mu is mapped to U+03BC.
But its name indicates it should be mapped to U+00B5.
The glyph named periodcentered is mapped to U+2219.
But its name indicates it should be mapped to U+00B7.

**Comment by huaiyukhaw** [comment]
Did you get the solution for this?

**Comment by vishal-vvr** [comment]
Hi @huaiyukhaw,
Yes i have fixed it[1], i am working on the release :)

[1] https://github.com/vishal-vvr/liberation-fonts/commit/ebafa6b5a7b39ec6fff2365dca45d7735d9cf84d

**Comment by pkgitlab** [comment]
Can you please describe what was the problem? I am facing same issue and I cannot access the link you pasted above.

**Comment by apoorvpotnis** [comment]
I see these warnings for New Computer Modern as well. Can you please if the warnings are genuine or spurious, and the solution if these are genuine?

> Hi [@huaiyukhaw](https://github.com/huaiyukhaw), Yes i have fixed it[1], i am working on the release :)
> 
> [1] https://github.com/vishal-vvr/liberation-fonts/commit/ebafa6b5a7b39ec6fff2365dca45d7735d9cf84d

This link seems broken.
