### ISSUE TITLE
U+25D2 and U+25D3 circle with lower / upper half black are backwards

### ISSUE THREAD

**Issue by srguiwiz** [liberationfonts/liberation-fonts#20]
If their names alone wouldn't say it, also see https://en.wikipedia.org/wiki/Harvey_Balls and https://www.fileformat.info/info/unicode/block/geometric_shapes/list.htm .

In CentOS 7.5 and 7.6 they are right in Liberation Mono, but backwards in Liberation Sans and Liberation Serif.

That should be an easy swap to fix.

More references https://www.fileformat.info/info/unicode/char/25d3/index.htm , https://www.fileformat.info/info/unicode/char/25d3/circle_with_upper_half_black.svg , https://www.fileformat.info/info/unicode/char/25d3/browsertest.htm , https://www.fileformat.info/info/unicode/char/25d3/fontsupport.htm .

They seem right for example in at least some Arial, Lucida, Free Sans.

For DejaVu both kind, right and wrong, can be found. Maybe for that font a fix is perlocating through the ecosystem.

This issue earlier had been brought up at https://pagure.io/liberation-fonts/issue/28 .

**Comment by vishalvvr** [comment]
Fixed in 2.1.0 release.
Thank you for reporting.
