### ISSUE TITLE
Gender symbol are inconsistent in Sans

### ISSUE THREAD

**Issue by brouillon** [liberationfonts/liberation-fonts#24]
Gender symbol female and male are not consistent with the other astrological symbols.
Problem of line thickness like Arial but especially smaller and shifted on the left

♀ | ♁ | ♂ | ♃ | ♄ | ♅ | ♆ | ♇

Screenshot Liberation sans with LO writer :
![Screenshot Liberation sans with LO writer](https://user-images.githubusercontent.com/2931266/65252759-cf3b6980-daf9-11e9-8968-9f53f5b9843d.png)

**Comment by kenmcd** [comment]
The larger bolder symbols are not present in Liberation Sans.
Only male (2640) and female (2642) exist.
LibreOffice will automatically replace characters which are missing in the applied font with characters from another font which does have those characters.
Those characters are most likely from Arial Unicode MS which does have all those astrological symbols.
The only way to check this that I am aware of is to _Export to PDF_ and then use your PDF reader to examine the fonts used for each character.
