### ISSUE TITLE
liberation-fonts doesn't have proper <==> symbol

### ISSUE THREAD

**Issue by pacho2** [liberationfonts/liberation-fonts#25]
It seems okular and evince are using LiberationSansRegular.ttf to render "Symbol" fonts in attached pdf but, sadly, <==> is not shown as can be seen in the page 10 of attached PDF file for
A + B ⇔ C≠ → P

**Comment by pacho2** [comment]
I don't know why github doesn't allow me to upload the pdf file :s
$ file 9-Propiedades_Termodinamicas_y_Constantes_Cineticas.pdf 
9-Propiedades_Termodinamicas_y_Constantes_Cineticas.pdf: PDF document, version 1.4

I uploaded it to my google drive
https://drive.google.com/file/d/1kUp6auKXqPBybwMSGBbbKiMo1pHhzKrk/view?usp=sharing

**Comment by pacho2** [comment]
mupdf renders it fine, but I guess it is because is using a different font than poppler based viewers that are using Liberation

**Comment by vishal-vvr** [comment]
Hello @pacho2,

The Symbol/Character you mentioned above is Unicode Character 'LEFT RIGHT DOUBLE ARROW' (U+21D4). When i tried to open your PDF in okular(on fedora 31 workstation) in properties is says it render Symbol from DejaVu Sans(system fonts).
![liberation-bug](https://user-images.githubusercontent.com/20382324/74626398-8275c080-5175-11ea-89a9-14c7f0cd8a0c.png)

Also liberation-fonts don't have this U+21D4 unicode character in any Liberation-fonts(monospace, sans and serif) family.

**Comment by pacho2** [comment]
In my case Liberation gets used
![Captura de pantalla de 2020-02-22 17-50-31](https://user-images.githubusercontent.com/923400/75096067-e9dba800-559b-11ea-891c-e1e6ff547f26.png)

**Comment by KrasnayaPloshchad** [comment]
See: https://en.wikipedia.org/wiki/Arrow_(symbol)

**Comment by vishalvvr** [comment]
fix available in 2.1.2 release.
Thank you for reporting.

**Comment by pacho2** [comment]
Thanks a lot
