### ISSUE TITLE
Liberation Mono: U+20BF is too wide

### ISSUE THREAD

**Issue by jengelh** [liberationfonts/liberation-fonts#33]
Between liberation-1.07.4 and liberation-2.1.1, Liberation has gained a new glyph, U+20BF BITCOIN SIGN, which is wider (1369 units) than most other glyphs past and present (1229 units).

This causes the "maximum advance width" as reported by libXft to change (X11/Xft/Xft.h: _XftFont::max_advance_width) and xterm to make character cells ~14% wider (1369/1229) as a result, leading to more whitespace between letters.

Is it really necessary for the glyph in question to break with the monospaceness of the font?

**Comment by vishalvvr** [comment]
fix available in 2.1.2 release.
Thank you for reporting.
