### ISSUE TITLE
Arabic alef with Hamza shows incorreclty on the previous lettre when used in combination with letter Laam

### ISSUE THREAD

**Issue by noelj62** [liberationfonts/liberation-fonts#43]
Hello,

For simplicity, I've included an image with visual indication to the issue:
![liberationfonts](https://user-images.githubusercontent.com/22582186/118394566-1458cb80-b64e-11eb-92b3-e2dd2bd55c91.png)

used software
OS: xubuntu 20.04 LTS
Libreoffice 6.4.7.2 and mousepad editor

Best regards,

**Comment by omeritzics** [comment]
> Hello,
> 
> For simplicity, I've included an image with visual indication to the issue:
> ![liberationfonts](https://user-images.githubusercontent.com/22582186/118394566-1458cb80-b64e-11eb-92b3-e2dd2bd55c91.png)
> 
> used software
> OS: xubuntu 20.04 LTS
> Libreoffice 6.4.7.2 and mousepad editor
> 
> Best regards,

Hello, this is not a problem in the Liberation fonts, since they do not support Arabic. This may be a problem in the [Noto fonts](https://github.com/googlefonts/noto-fonts).

**Comment by vishalvvr** [comment]
Sorry for the late reply and Thank you @omeritzics for acknowledging first.
This is not an liberation-fonts issue, this is rendering issue caused by alternate font(mostly noto fonts).
