### ISSUE TITLE
Adopt Carlito and Caladea into the Liberation Fonts family

### ISSUE THREAD

**Issue by Eonfge** [liberationfonts/liberation-fonts#44]
Delving a bit deeper into the history and configuration of fonts, I found that the latest versions of the Liberation Fonts, are essentially updated version of Googles' core fonts project, which aimed at providing substitutes for Arial, Times New Roman and Courier New.

Google didn't stop there though, and they later made an corextra package that contains two more fonts:

- Carlito (MS Calibri replacement)
- Caladea (MS Cambria replacement)

https://en.wikipedia.org/wiki/Croscore_fonts

As such, I was wondering, could those also be adopted into the Liberations Font project? Google themselves seems to give them very little attention.

sources:
- https://gsdview.appspot.com/chromeos-localmirror/distfiles/crosextrafonts-20130214.tar.gz
- https://gsdview.appspot.com/chromeos-localmirror/distfiles/crosextrafonts-carlito-20130920.tar.gz

**Comment by Erick555** [comment]
Isn't it dupe of https://github.com/liberationfonts/liberation-fonts/issues/16 ?

**Comment by Eonfge** [comment]
It totally is. Let's close this one up and let's add my comments there.
